# Grok-4-0709 Model Configuration
models:
  grok:
    provider: "openrouter"
    model_id: "x-ai/grok-4-0709"
    api_endpoint: "https://openrouter.ai/api/v1"
    
    # Model parameters
    parameters:
      max_tokens: 8192
      temperature: 0.7
      top_p: 0.95
      frequency_penalty: 0.0
      presence_penalty: 0.0
      
    # Specialized configurations for different tasks
    configurations:
      pattern_analysis:
        temperature: 0.3
        max_tokens: 4096
        system_prompt: |
          You are Grok-4-0709, an advanced AI specialized in smart contract pattern analysis.
          Focus on identifying architectural patterns, optimization opportunities, code quality metrics,
          and innovative approaches in smart contract design. Provide constructive insights.
          
      gas_optimization:
        temperature: 0.2
        max_tokens: 4096
        system_prompt: |
          You are Grok-4-0709, analyzing smart contracts for gas optimization opportunities.
          Identify storage optimizations, function selector optimizations, and other gas-saving patterns.
          Provide specific, actionable recommendations.
          
      innovation_scoring:
        temperature: 0.4
        max_tokens: 2048
        system_prompt: |
          You are Grok-4-0709, evaluating smart contract innovation and design quality.
          Score contracts based on novel approaches, creative solutions, and best practices.
          
    # Rate limiting
    rate_limits:
      requests_per_minute: 60
      tokens_per_minute: 100000
      concurrent_requests: 10
      
    # Retry configuration
    retry:
      max_attempts: 3
      initial_delay: 1
      max_delay: 60
      exponential_base: 2
      
# Authentication
authentication:
  method: "bearer"
  key_env_var: "GROK_API_KEY"
  
# HTTP client configuration  
http_client:
  timeout: 300
  connection_timeout: 30
  read_timeout: 300
  
# Response handling
response:
  format: "json"
  streaming_enabled: true
  parse_json_responses: true
  
# Caching configuration
cache:
  enabled: true
  ttl: 3600
  max_size: 1000