# Grok-4-0709 Model Configuration
models:
  grok:
    provider: "openrouter"
    model_id: "x-ai/grok-4-0709"
    api_endpoint: "https://openrouter.ai/api/v1"
    
    # Model parameters
    parameters:
      max_tokens: 8192
      temperature: 0.7
      top_p: 0.95
      frequency_penalty: 0.0
      presence_penalty: 0.0
      
    # Specialized configurations for different tasks
    configurations:
      analysis:
        temperature: 0.3
        max_tokens: 4096
        system_prompt: |
          You are Grok-4-0709, an advanced AI specialized in Ethereum smart contract security analysis.
          Focus on identifying vulnerabilities: reentrancy, integer overflow, access control, oracle manipulation,
          flash loan attacks, MEV opportunities, and other DeFi-specific vulnerabilities.
          
      exploit_generation:
        temperature: 0.2
        max_tokens: 8192
        system_prompt: |
          You are Grok-4-0709, generating production-ready Solidity exploit code.
          Generate complete, working exploit contracts optimized for Ethereum mainnet.
          Include all necessary imports, interfaces, error handling, and gas optimizations.
          
      planning:
        temperature: 0.4
        max_tokens: 4096
        system_prompt: |
          You are Grok-4-0709, creating detailed exploit execution plans.
          Consider gas costs, slippage, MEV protection, and profit optimization.
          
    # Rate limiting
    rate_limits:
      requests_per_minute: 60
      tokens_per_minute: 100000
      concurrent_requests: 10
      
    # Retry configuration
    retry:
      max_attempts: 3
      initial_delay: 1
      max_delay: 60
      exponential_base: 2
      
# Authentication
authentication:
  method: "bearer"
  key_env_var: "GROK_API_KEY"
  
# HTTP client configuration  
http_client:
  timeout: 300
  connection_timeout: 30
  read_timeout: 300
  
# Response handling
response:
  format: "json"
  streaming_enabled: true
  parse_json_responses: true
  
# Caching configuration
cache:
  enabled: true
  ttl: 3600
  max_size: 1000